### ISSUE TITLE
[RFE] Add alerts runbooks as a new data source for the LLM of OCP Lightspeed

### ISSUE THREAD

**Issue by sradco** [openshift/lightspeed-service#888]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add alerts runbooks as a new data source for the LLM of OCP Lightspeed
Alerts runbooks have a defined structure and can be a good source of information for the LLM to learn about how an alert 
impacts and how to diagnose and mitigate it.

The OCP alerts runbooks are located in https://github.com/openshift/runbooks/blob/master/alerts
For example,https://github.com/openshift/runbooks/blob/master/alerts/openshift-container-storage-operator/PersistentVolumeUsageCritical.md is a runbook for the PersistentVolumeUsageCritical alert.
These runbooks have been reviewed by engineers and Red Hat docs team.

There are additional upstream runbooks that we might also be able to add like:
- https://containersolutions.github.io/runbooks/posts/kubernetes/
- https://github.com/prometheus-operator/runbooks

**Describe alternatives you've considered**

**Additional context**

**Comment by bparees** [comment]
converted to jira issue [OLS-617](https://issues.redhat.com/browse/OLS-617)
