### ISSUE TITLE
[RFE] Add to OCP Lightspeed the ability to generate PromQL queries

### ISSUE THREAD

**Issue by sradco** [openshift/lightspeed-service#889]
**Is your feature request related to a problem? Please describe.**

As an SRE/manager I want to be able to use the chat bot to ask in natural language what I'm interested about and that get the PromQL query from it that I will be able to just copy and paste to Grafana/OCP metrics page.
 
**Describe the solution you'd like**

Prometheus is installed by default in most of the the OCP installation.
It would be useful to integrate and teach the the LLM how to query Prometheus for our users.
Prometheus enables the users to query information for current state and also for a period of time.
For example a question that a user can ask the AI: 
write a PromQL query, Show me the trend of requests latency in the network during the last day.

I think that a plain Prometheus LLM would not be sufficient since we need to teach the module the OCP language vocabulary. For example, what is a VM and a Virtual Machine and how they are connected to the metrics. 

**Describe alternatives you've considered**

**Additional context**

**Comment by bparees** [comment]
@sradco i'm not totally clear on what you're asking for/proposing with this issue.  

Is it fundamentally a suggestion that OLS be used to generate promQL queries for users?  Presumably with some knowledge(RAG or fine-tuning) that enables the model to understand the specific metrics available in OCP and what they represent (in addition to the model needing the ability to know how to generate valid promQL syntax)?

Do you foresee new UI flows associated w/ this, or users would just type a natural language query into the OLS chat and get back a promQL statement they can paste into the query interface?  (obvious improvements would be giving users a natural language prompt in the query interface, or having OLS able to populate the promQL query bar, but i'm not sure if you're proposing that level of integration or not)

A worked example or some user stories might be helpful to flesh out your idea here.

**Comment by sradco** [comment]
Hi @bparees , I updated the description, based on our offline conversation.
I see this as an important feature for SREs that want to query Prometheus and are not very familiar with PromQL.
They usually are interested in both running ad-hoc queries and also creating custom dashboards.

As discussed off line, my idea is to start small and work to create a pull of questions and answers per operator/OCP component.
This can be the base to use NLP and LLM for creating the ability for the chat bot to be able to generate PromQL queries that are specific to OCP.

We can think of creating a dedicated repository like the openshift/runbooks in Github where this can be collected in. For example: openshift/promql-query-examples and set best practices for the required structure that data needs to be in.
This can be the base for this work.
